version: '3.8'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    container_name: rev3rsi-deploy
    #env_file:
    #  - .env.dev
