# Generated by Django 4.1.5 on 2023-01-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversi', '0004_gamedb_score_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='player1',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='gamedb',
            name='player2',
            field=models.CharField(max_length=24),
        ),
    ]
