# Generated by Django 4.1.5 on 2023-01-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversi', '0005_alter_gamedb_player1_alter_gamedb_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='next_player',
            field=models.IntegerField(default=1),
        ),
    ]
