# Generated by Django 4.1.5 on 2023-01-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversi', '0006_gamedb_next_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
